# Generated by Django 4.0.2 on 2022-02-27 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('nombres', models.CharField(max_length=50, null=True, verbose_name='Nombres')),
                ('apellido_uno', models.CharField(max_length=50, null=True, verbose_name='Primer Apellido')),
                ('apellido_dos', models.CharField(max_length=50, null=True, verbose_name='Segundo Apellido')),
                ('cedula', models.CharField(max_length=50, null=True, verbose_name='Cedula')),
                ('fecha_nacimiento', models.DateField(max_length=150, null=True, verbose_name='Fecha de nacimiento')),
                ('genero', models.CharField(max_length=50, null=True, verbose_name='Genero')),
                ('fecha_Ingreso', models.DateField(max_length=150, null=True, verbose_name='Fecha de ingreso')),
                ('numeroempleado', models.CharField(max_length=50, null=True, verbose_name='Numero empleado')),
                ('cargo', models.CharField(max_length=50, null=True, verbose_name='Cargo')),
                ('zona', models.CharField(max_length=50, null=True, verbose_name='Zona')),
                ('municipio', models.CharField(max_length=50, null=True, verbose_name='Municipio')),
                ('departamento', models.CharField(max_length=50, null=True, verbose_name='Departamento')),
                ('ventas_anteriores', models.CharField(max_length=50, null=True, verbose_name='Ventas')),
                ('contraseña', models.CharField(max_length=50, null=True, verbose_name='Contraseña')),
                ('imagen', models.CharField(max_length=50, null=True, verbose_name='Imagen')),
                ('celular', models.CharField(max_length=50, null=True, verbose_name='Celular')),
                ('jefe', models.CharField(max_length=50, null=True)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('date_of_birth', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuario',
                'db_table': 'usuario',
                'ordering': ['id'],
            },
        ),
    ]
