# Generated by Django 4.0.2 on 2022-02-26 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=50, null=True, verbose_name='Cedula')),
                ('fecha_nacimiento', models.DateField(null=True, verbose_name='Fecha')),
                ('genero', models.CharField(max_length=50, null=True, verbose_name='Genero')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuario',
                'db_table': 'usuario',
                'ordering': ['id'],
            },
        ),
    ]
