# Generated by Django 4.0.2 on 2022-02-26 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='cargo',
            field=models.CharField(max_length=50, null=True, verbose_name='Cargo'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='celular',
            field=models.CharField(max_length=50, null=True, verbose_name='Celular'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='contraseña',
            field=models.CharField(max_length=50, null=True, verbose_name='Contraseña'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='departamento',
            field=models.CharField(max_length=50, null=True, verbose_name='Departamento'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=50, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='fecha_Ingreso',
            field=models.DateField(max_length=150, null=True, verbose_name='Fecha de ingreso'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='imagen',
            field=models.CharField(max_length=50, null=True, verbose_name='Imagen'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='municipio',
            field=models.CharField(max_length=50, null=True, verbose_name='Municipio'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='numeroempleado',
            field=models.CharField(max_length=50, null=True, verbose_name='Numero empleado'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='ventas_anteriores',
            field=models.CharField(max_length=50, null=True, verbose_name='Ventas'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='zona',
            field=models.CharField(max_length=50, null=True, verbose_name='Zona'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fecha_nacimiento',
            field=models.DateField(max_length=150, null=True, verbose_name='Fecha de nacimiento'),
        ),
    ]
