# Generated by Django 4.0.2 on 2022-02-26 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_usuario_cargo_usuario_celular_usuario_contraseña_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='apellido_dos',
            field=models.CharField(max_length=50, null=True, verbose_name='Segundo Apellido'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='apellido_uno',
            field=models.CharField(max_length=50, null=True, verbose_name='Primer Apellido'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='nombres',
            field=models.CharField(max_length=50, null=True, verbose_name='Nombres'),
        ),
    ]
