# Generated by Django 4.0.2 on 2022-02-26 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0003_usuario_apellido_dos_usuario_apellido_uno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='jefe',
            field=models.IntegerField(null=True),
        ),
    ]
