# Generated by Django 4.0.2 on 2022-02-26 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0004_usuario_jefe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='jefe',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
